import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Button from "@mui/material/Button";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Code by Michael Farrelly</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <p>Try out a game, like:</p>
                <Link href="/wordlelike" passHref>
                    <Image
                        src="/WordleLike.png"
                        alt="WordleLike"
                        width="480"
                        height="360"
                    />
                </Link>

                <Button variant="contained" color="primary" href="/wordlelike">
                    Wordle-Like
                </Button>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
};

export default Home;
