import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import styles from "../styles/Home.module.css";
import Keyboard from "./keyboard";

import WordGuess from "./wordguess";

const Home: NextPage = () => {
    const [letters, setLetters] = React.useState<string[]>([
        "S",
        "A",
        "B",
        "O",
        "Y",
    ]);
    const [outOfPositionLetters, setOut] = React.useState<string[]>(["A"]);
    const [okLetters, setOk] = React.useState<string[]>(["S"]);
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>Wordle</h1>
                <p className={styles.description}>How to play the game.</p>
                <div className={styles.grid}>
                    <div>Guesses</div>
                    <WordGuess word={"Sassy"} master="Stool" />
                    <WordGuess word={"Bossy"} master="Stool" />
                </div>
                <div className={styles.keyboard}>
                    <Keyboard
                        letters={letters}
                        okLetters={okLetters}
                        outOfPositionLetters={outOfPositionLetters}
                    ></Keyboard>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
};

export default Home;
