import { Box } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import { Wordle } from "../components/wordle";
import styles from "../styles/WordleLike.module.css";

const WordleLike: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Wordle-Like</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <link
                    rel="stylesheet"
                    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
                />
            </Head>

            <Box
                sx={{
                    width: "90%",
                    height: "100%",
                }}
            >
                <Wordle />
            </Box>
        </div>
    );
};

export default WordleLike;
